-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

-- CREATE TABLES
CREATE TABLE Category(
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    category_name VARCHAR(30) NOT NULL
)

CREATE TABLE Product(
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL(3,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 10,
    category_id INTEGER,
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE CASCADE;
)

CREATE TABLE Tag(
    id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    tag_name VARCHAR(30)
)

CREATE TABLE ProductTag(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    product_id INTEGER,
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES Product(id) ON DELETE CASCADE,
    tag_id INTEGER,
    CONSTRAINT fk_tag_id FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE CASCADE
)